<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?=$title?></title>
        <script     src="/assets/js/vue.js"></script>
        <script src="/assets/js/jquery3.js"></script>
        <script   src="/assets/js/twbs4.js"></script>
        <link rel="stylesheet" href="/assets/css/twbs4.css">
    </head>
    <body>
        <div id="app">
            {{ message }}
        </div>
    </body>
</html>

<?php $viewname = preg_replace('/.php$/', '', basename($_SERVER['SCRIPT_FILENAME'])); ?>
<?php $D = new \DirectoryIterator($SITE_DIR . 'public/assets/js/'); ?>
<?php foreach($D as $f): ?>
<?php if (preg_match('/' . $viewname . '.js$|' . $vuename . '.js$/m', $f)): ?>
<script src="<?=$SITE_URL?>assets/js/<?=$f?>"></script>
<?php endif; ?>
<?php endforeach; ?>
