<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?=$title?></title>
        <script     src="/assets/js/vue.js"></script>
        <script src="/assets/js/jquery3.js"></script>
        <script   src="/assets/js/twbs4.js"></script>
        <link rel="stylesheet" href="/assets/css/twbs4.css">
        <link rel="stylesheet" href="/assets/css/main.css?<?=rand()?>">
        <link rel="stylesheet" href="/assets/css/fa.css">
    </head>
    <body>
        <div id="app">
            <header-main></header-main>
            <div class="container-fluid">
                <public-home></public-home>
            </div>
        </div>
    </body>
</html>
<script src="http://dps/assets/vues/components.js"></script>
<script src="http://dps/assets/vues/index.js"></script>
