<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?=$title?></title>
        <script     src="/assets/js/axios.js"></script>
        <script     src="/assets/js/vue.js"></script>
        <script src="/assets/js/jquery3.js"></script>
        <script   src="/assets/js/twbs4.js"></script>
        <link rel="stylesheet" href="/assets/css/twbs4.css">
        <link rel="stylesheet" href="/assets/css/main.css?<?=rand()?>">
        <link rel="stylesheet" href="/assets/css/fa.css">
    </head>
    <body>
        <div id="app">
            <header-main></header-main>
            <div class="container-fluid">
            	<div>
                	<label style="margin-right:10px;">Enter a postcode to search:</label>
    				<input v-model="location" type="text"></input>
    				<button @click="searchLocation">Search</button>
    			</div>
    			<div v-if="stations" style="display:flex; flex-direction: column;" >
    				
    				<petrol-station-card 
    				v-for="(station, index) in stations"
    				:station="station"
    				:index="index"
    				:key="station.code">
    				</petrol-station-card>
    			</div>
         	</div>
        </div>
    </body>
</html>
<script src="http://dps/assets/vues/components.js"></script>
<script src="http://dps/assets/vues/location.js"></script>
