<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?=$title?></title>

        <script src="/assets/js/jquery3.js"></script>
        <script   src="/assets/js/twbs4.js"></script>
        <link rel="stylesheet" href="/assets/css/twbs4.css">
        <link rel="stylesheet" href="/assets/css/main.css?<?=rand()?>">
        <link rel="stylesheet" href="/assets/css/fa.css">
    </head>
    <body>
        <p>Hello</p>
        <pre>
        <?php
            print_r($petrol);
        ?>
        </pre>

    </body>
</html>
